version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/email_ai
      - JWT_SECRET_KEY=your_super_secret_key_for_development_only
      - REDIS_HOST=redis
      - ENVIRONMENT=development
      - OPENAI_API_KEY=sk-dummy-key
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:8000/api/google/callback
    volumes:
      - ./backend:/app/backend
      - ./alembic:/app/alembic
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A backend.worker worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/email_ai
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./backend:/app/backend
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  redis_data: 