name: Database Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Daily backup at midnight

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      
      - name: Create Backup
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku pg:backups:capture --app email-ai-app
          heroku pg:backups:download --app email-ai-app 